name: doner-frontend
services:
  doner-frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://doner-api.mynet.local:3000
    image: doner-frontend
    container_name: doner-frontend
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      rwznet:
        ipv4_address: 10.31.13.176

networks:
  rwznet:
    external: true