services:
  doner-backend:
    build: 
      context: .
    container_name: doner-backend
    restart: always
    networks:
      rwznet:
        ipv4_address: 10.31.13.175
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  rwznet:
    external: true